### ISSUE TITLE
ドキュメント記載のコマンドを実行でROS2 packageのインストールが失敗する

### ISSUE THREAD

**Issue by grace2riku** [TE-YoshinoriOota/Spresense-microROS-Seminar#3]
つぎのドキュメントで記載コマンドが一部不足していてエラーになりました。

* ドキュメント
  * Documents/Get started microROS programming with Sony Spresense.pdf
  * Documents/Spresense とmicro-ROS ではじめるロボットプログラミング.pdf

* 該当ページ
p16
Development Environment
ROS2 Setup
【STEP2】 Install ROS2 package

* 該当箇所
sudo apt update && sudo upgrade

* 確認
sudo apt upgradeの**apt**がないようでした。
つぎのコマンドで実行できました。
sudo apt update && sudo apt upgrade

ご確認よろしくお願いします。

**Comment by TE-YoshinoriOota** [comment]
ご指摘ありがとうございます。
Page 16 の記述を修正いたしました。ご確認いただけるでしょうか？
対応が大変遅くなりまして、失礼をいたしました。

**Comment by grace2riku** [comment]
ご確認・ご対応ありがとうございます。
日本語ドキュメントの修正を確認しました。
クローズします。

※英語版も修正いただけると良いかと思います。

**Comment by grace2riku** [comment]
close
