### ISSUE TITLE
SprTurtleBotの3Dプリンタ設計データについて

### ISSUE THREAD

**Issue by grace2riku** [TE-YoshinoriOota/Spresense-microROS-Seminar#4]
お世話になります。

Spresense とmicro-ROS ではじめるロボットプログラミング.pdfの手順で
PID調整プログラムの動作を確認できました。
ありがとうございます。

p53 SprTurtleBotの3Dプリントの製作物について3Dプリンタの設計データ(STLファイル)、下記の情報を公開していただくことは可能でしょうか?
具体的にはつぎになります。

* p53 仕様部材表 基板台座
* p53 仕様部材表 バッテリー台座
* カメラのケース
* バッテリー台座に収めるバッテリーの型番(YouTube動画を見る限りSONYのCP-V3かと思っています)

ご検討、よろしくお願いいたします。

**Comment by TE-YoshinoriOota** [comment]
resource フォルダにSTLファイルをおいておきました。ご自由にお使いください。
バッテリーは廃棄してしまっており、残念ながら型番がわかりません。（ソニー製ではなかったと思います）
バッテリーの台座が 95mm x 24mm で設計していますので、その大きさのものを探していただけますでしょうか？
私は、小型スティック型モバイルバッテリ（2000mAh程度）を使っていました。

**Comment by grace2riku** [comment]
ご対応ありがとうございます。
バッテリの件も情報ありがとうございます。承知しました。

本件はこれでクローズします。
